### ISSUE TITLE
새 오프셋 템플릿 - DHC 디젤동차

### ISSUE THREAD

**Issue by EightonEight** [EightonEight/KoreanTrainSet#2]
이미 수정된 새마을호 객차([KoreanGRF#429](https://github.com/KoreanGRF/KoreanTrainSet/issues/429))를 기준으로 수정
참고할만한 열차 운전실 - 이음, ITX 등
중련 가능 열차로, 확장 템플릿을 적용하면 **좀 많이 겹침** → 표준 템플릿 사용

연결기마개 있음/없음 무작위 표출 기능 추가?

**Comment by SerpensNebula** [comment]
DHC 제가 작업해도 될까요?

**Comment by EightonEight** [comment]
> DHC 제가 작업해도 될까요?

네 가능합니다.
